# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Base info
mc_version=26.1.2
neo_version=26.1.2.29-beta
mod_group=com.mrbysco.oreberriesreplanted
mod_id=oreberriesreplanted
mod_archive_name=OreBerries-Replanted

#Publishing
mod_name=Oreberries Replanted
curseforge_id=454062
modrinth_id=no8wHvOG

# Version
version=0.12.1

# Support info
jei_minecraft=26.1.2
jei_version=29.5.0.26
rei_version=21.11.814
architectury_version=19.0.1
cloth_config_version=21.11.153
bookshelf_version=21.1.67
botanypots_version=16.1.5