# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Base info
mc_version=1.21.8
neo_version=21.8.31
neogradle.subsystems.parchment.minecraftVersion=1.21.8
neogradle.subsystems.parchment.mappingsVersion=2025.07.20
neogradle.subsystems.conventions.runs.create-default-run-per-type=false
mod_group=com.mrbysco.oreberriesreplanted
mod_id=oreberriesreplanted
mod_archive_name=OreBerries-Replanted

#Publishing
mod_name=Oreberries Replanted
curseforge_id=454062
modrinth_id=no8wHvOG

# Version
version=0.10.1

# Support info
jei_version=24.0.0.2
rei_version=20.0.811
architectury_version=17.0.8
cloth_config_version=19.0.147
bookshelf_version=21.1.67
botanypots_version=16.1.5